### ISSUE TITLE
Crack Hammer 1.1.45 [1.15.2]

### ISSUE THREAD

**Issue by Mikeliro** [kwpugh/easy_steel#13]
1. Often, when I click on a block that is on top of me in the cave with the right mouse button using Crack Hammer, the item gets stuck on the wall and rises to the surface.

2. If you right-click on a block that Crack Hammer does not break, it will wear out.

**Comment by kwpugh** [comment]
1. Still looking into this
2. Fixed in v1.1.46

**Comment by kwpugh** [comment]
1.  Crack hammer and hand shovel fixed. 

Need to fix flint shovel.

**Comment by kwpugh** [comment]
Since I changed the crack hammer to a crafting item, this is no longer an issue.
