### ISSUE TITLE
Somehow breaks leaf distance

### ISSUE THREAD

**Issue by Magnymbus** [kwpugh/easy_steel#2]
While this mod is installed with forge-28.1.96, all leaves register distance as 7 (max distance at which leaves decay) regardless of the actual distance to a log. This causes ALL LEAVES to decay as soon as a tree is loaded into random tick radius.

**Comment by kwpugh** [comment]
Can you give me some more details.   I have been playing for several hours on my own server with the latest Easy Steel and forge 96 and this does not seem to happen.   Nothin in my mod does anything to leave blocks.  This behavior sounds more like a fast leaf decay mod.

**Comment by jwrichards1982** [comment]
Same here.  Forge 28.1.96, 96 mods installed, leaves decay.  Remove Easy Steel 1.0.50.  leaves no longer decay.  Spent a few hours rolling back Forge version and slowly taking out the mods that previously worked fine together due to needing the exact forge version and got down to 28.1.79...after 3 hours and still finding Easy Steel being the only change to the mod list that previously played well together, leaves would start decaying everywhere on a new world gen.  

I have a save from another instance which I THINK had Easy Steel installed previously and it didn't have decaying leaves...  but even on that instance when loading a generate a new world they too would start to decay.  I would roll back to an older version of Easy Steel, but after 3 hours playing around with this already, I lost all interest in playing games for a while... :(

**Comment by jwrichards1982** [comment]
Okay.  So.  i couldn't let this go and decided to setup a new instance and install just Easy Steel.  Sure enough.  1.0.50 causes leaves to decay on Forge 28.1.96.  Now...I do remember playing with it before, so I looked back in my history and started using Easy Steel at version 1.0.44.  So, I downloaded each version up to now. 

In an instance with JUST Easy Steel installed, I would remove all settings and configs each time and would generate a new world.  Whatever changes happened between 1.0.49, to 1.0.50, leaves now decay on a fresh generated world and instance.  

So.  I took my original mod setup, new instance, dropped in 1.0.49, fresh generated configs and all.  Generated a new world.  No leaves decaying.  So...whatever changed between 1.0.49 and 1.0.50 is causing leaves to decay.

In trying to add more...  Generate a new world with 1.0.49, run a round for a while.  No leaves decay.  save and quit.  Delete the config.  Replace 1.0.49 with 1.0.50, start up the saved world, everything seems fine until a run out q good distance to begin new chunk generation and POOF.  Leaves begin decaying in the newly generated areas.  This is replicated in both a modded setting and JUST easy steel.  i also noticed different aberrant behaviors.  One was in a modded setting where I could not put on a necklace from the Enigmatic Legacy as long as 1.0.50 was installed.  Jumping didn't feel fluid and I would sink immediately below water.  No floating or slow sinking, as if water blocks had the properties of air.

**Comment by kwpugh** [comment]
Interesting.   v50 only had 5 changes; a new emerald powder, a recipe, a forge tag, some logic on the crack hammer to add a drop of powder from emerald ore, and Forge 96.

Everything but the Forge change does not explain the leaf decay.

This is truly bizarre.  

If I create a new world then exit, then add Easy Steel v50 and rejoin, no problem.   However, if I create a new world with Easy Steel, the leaf decay happens.

I am still fairly new to java coding and I cannot determine what in the changes I made (simple stuff), could cause such a thing.   I am going to create a version of v50 with the previous Forge version it had and see if it still does this.

**Comment by kwpugh** [comment]
So I tried building a version of the latest code but dropped the Forge version to 92 and ran it again on the client with 96 installed.  Same decay problem.

Then I tried it on a client running v92 of Forge, no problem.   I rebuilt the mod again with 96 forge and ran it on a client with 92, no decay.  Makes me think it might be a problem with the way forge 96 is running on the client.

Please try running the current Easy Steel v50 on a client running Forge 92 and confirm/deny wether the decay problem happen for you folks.

**Comment by kwpugh** [comment]
Try this file with Forge 96 on the client and see if it persists.


[EasySteel-1.14.4-1.0.51.jar.zip](https://github.com/kwpugh/easy_steel/files/3903742/EasySteel-1.14.4-1.0.51.jar.zip)

**Comment by kwpugh** [comment]
I posted a new version to Curseforge that by my testing eliminates.   Let me know if otherwise.

**Comment by jwrichards1982** [comment]
I was at work and VERY busy the last couple days.  I have it running on Forge 96, and in a new world, no decay.  Going to look at 92 now.

Test:
Easy Steel ONLY, New world each time, config deleted between each load.  Survival,, no custom seed
Forge 92, Easy Steel .49 -> No leaf decay
Forge 92, Easy Steel .50 -> Yes leaf decay
Forge 96, Easy Steel .49 -> No leaf decay
Forge 96, Easy Steel .50 -> Yes leaf decay

Easy Steel ONLY, World reloaded each time, config deleted between each load.  Survival,, no custom seed
Forge 92, Easy Steel .49 -> No leaf decay
Forge 92, Easy Steel .50 -> Yes leaf decay
Forge 96, Easy Steel .49 -> No leaf decay
Forge 96, Easy Steel .50 -> Yes leaf decay
NOTE - when making the world on .49, I stayed in one spot.  Let all the immediate chunks load, waited a bit longer and saved.  Upon switching to .50 and loading the world, all the leaves in the known chunks did not decay.  Running toward a new set of chunks, leaves began to decay.  Upon running back to reload the original chunks...no leaf decay.  .50 does something to world gen on newly "found" chunks and the leaf decay mechanic...

So...  I would hasten to guess that a world loaded with .49 and saved, then updating to .50, Easy Steel has issues with NEW generated chunks in a world previously on .49, which might explain why it wasn't seen until one of us went somewhere else.  .51 seems to resolve that issue, no leaf decay that I can find.

This what you were looking for?  Does it help?  Maybe leaning on the forge team might shed some light on it...

**Comment by kwpugh** [comment]
Thank you for the clarity.

Did you try out the .51 to make sure you were not getting leaf decay anymore?

**Comment by kwpugh** [comment]
No more reports of issues with v51.

**Comment by jwrichards1982** [comment]
Apologies.  Very busy lately at work.  But, yes.  .51 resolved the leaf decay issue.

**Comment by kwpugh** [comment]
Wonderful.
