### ISSUE TITLE
Setting OreGeneration to false in config does not prevent generation

### ISSUE THREAD

**Issue by danemorgan** [kwpugh/easy_steel#21]
Minecraft: 1.16.4
Forge: 35.1.36
Easy Steel: EasySteel-1.16.5-1.2.18

With this combo, ores that I set to false still generated. Dropping back down to the last 1.16.4 version of Easy Steel makes the config work correctly.

**Comment by kwpugh** [comment]
you try it on 1.16.5?

**Comment by danemorgan** [comment]
No. I tried it as described. I'm using the Curseforge launcher and so far they have not added a 1.16.5 version of Forge to the launcher.

**Comment by kwpugh** [comment]
which ores did you disable in config?

**Comment by danemorgan** [comment]
All of them actually. I'm only using it for steel production. And in fairness, I didn't go hunting for other ores, and the one I saw on the surface was Cassiterite. Then I was looking for a solution and noticed the version number mismatch. I downgraded, deleted the world, restarted it and the Casserite was no longer there.

**Comment by kwpugh** [comment]
downgraded what?

**Comment by kwpugh** [comment]
you do know that disabling the ore inn the config only affects checks loaded after you disable it, correct?

It does not remove ores already spawned in loaded chunks.

**Comment by danemorgan** [comment]
Yes, I do. I was creating a new world. When I saw the ore generated, I looked for a reason, downgraded, deleted the just created world, and created it again. Same seed.

**Comment by danemorgan** [comment]
Downgraded the version of easy steel. I downgraded from EasySteel-1.16.5-1.2.18 to EasySteel-1.16.4-1.2.14.jar. and this fixed the issue for me.

**Comment by kwpugh** [comment]
I tried:

Minecraft: 1.16.4
Forge: 35.1.36
Easy Steel: EasySteel-1.16.5-1.2.18

Disabled all ores in easy steel config and not a single easy steel ore was spawned.

**Comment by danemorgan** [comment]
Okay. Sorry. Must be something I did wrong.
