### ISSUE TITLE
[1.17.1] Let Flint Knife More Balanced

### ISSUE THREAD

**Issue by 1mtwtfss1** [kwpugh/easy_steel#22]
Flint Knife can obtain string from sheep almost infinitely, but sheep's wool will not disappear. So you can get almost infinite wool if you have enough gravel. It is a little unbalanced. I think sheep can be sheared if a player used a Flint Knife on them too many times.

**Comment by kwpugh** [comment]
added to latest 1.17.1 and 1.18 version.  Hook knife takes damage and "shears" the sheep having a builtin delay as a result.
