### ISSUE TITLE
[1.18.1] Couldn't load tag

### ISSUE THREAD

**Issue by XxRexRaptorxX** [kwpugh/easy_steel#24]
MC 1.18.1
Mod: 1.5.7

`
[00:27:31] [Worker-Main-12/ERROR]: Couldn't load tag easy_steel:paxel_mineable as it is missing following references: #minecraft:mineable/pickaxe (from EasySteel-Forge-1.18.1-1.5.7.jar)
00:27:33.673
game
[00:27:33] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
00:27:33.673
game
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Missing required tags: ResourceKey[minecraft:root / minecraft:block]:easy_steel:paxel_mineable,ResourceKey[minecraft:root / minecraft:block]:minecraft:mineable/pickaxe,ResourceKey[minecraft:root / minecraft:block]:minecraft:needs_stone_tool`

**Comment by kwpugh** [comment]
Did you disable some of the tools?

**Comment by kwpugh** [comment]
I cannot replicate this on single player or  my test server.  I  will need more info to understand what might be  happening.

**Comment by XxRexRaptorxX** [comment]
it turned out that the problem was caused by another mod

**Comment by kwpugh** [comment]
which one, so I know if it comes up again?

**Comment by XxRexRaptorxX** [comment]
hard to tell, it occurred in a modpack. after deactivating some mods and reactivating them again, the bug just went away

**Comment by kwpugh** [comment]
Ok, I know how that is.  If you do figure which one, could you put an update here?  Thanks.
