### ISSUE TITLE
[1.18.1] Blast Furnace takes too long to smelt ore

### ISSUE THREAD

**Issue by Shadow00x7** [kwpugh/easy_steel#25]
Ight, so it's been a week, I am playing on a modded server, with Easy steel mods installed but however, if we try to smelt Ores exclusive to Easy Steel in Blast Furnace, it takes regular 10s (same as normal furnace) to smelt, causing the fuel to run out faster. Dunno, if it is intentional, but however, this is really annoying.

**Comment by kwpugh** [comment]
That shouldn't have been longer, let me check.

**Comment by Shadow00x7** [comment]
Also i forgot to mention, the game version is 1.16.5

**Comment by kwpugh** [comment]
oh, I'm not really updating 1.16.5 anymore, but I will see.

**Comment by kwpugh** [comment]
For 1.16.5 version:  adjust in v1.2.23 pushed to curse forge

For 1.17.1 - skipping, no longer supported.

Working on 1.18.1

**Comment by kwpugh** [comment]
Adjust version for 1.18.1
