### ISSUE TITLE
[1.19.2] Hammers are invulnerable and their durability only continues into the negatives once it passes zero.

### ISSUE THREAD

**Issue by aspenatr** [kwpugh/easy_steel#28]
Excavators do this as well. There seems to be no distinguishment between ore type & the issue at hand with either - though I haven't captured that.

I am playing on a heavily modded pack and have not tested this alone. 100% willing to elaborate.

Game ver is 1.19.2. Mod ver is EasySteel-Forge-1.19.2-1.6.11, downloaded as the latest from the CurseForge/OverWolf modpack client.

https://user-images.githubusercontent.com/114365990/192167604-532a348f-e719-4a17-9d68-7cf870a763b9.mp4

**Comment by kwpugh** [comment]
Ok, I think I got it fixed.  I will push a new build to curse forge.

Also, I'm adding in a new full damage feature to the hammers and excavators, so durability loss will match number of blocks broken.  There is a new config option to turn that off if you want the older method.

**Comment by kwpugh** [comment]
should be fixed now in v1.6.12

let me know if you have any other issues.
