### ISSUE TITLE
Titanium ingots/blocks are interchangeable with silver

### ISSUE THREAD

**Issue by ShadowRyuu06** [kwpugh/easy_steel#29]
Crafting titanium into blocks gives the option to make silver blocks from other mods.
and the same with the other way around.

After a bit of rummaging around this mod and a few others, it seems that this mod has titanium tagged as silver in forge. 
Is this intentional or was it a mistake?

**Comment by kwpugh** [comment]
Yes, that was intentional due to a lack of easy mods that provided silver ingots.  It can be removed via a data pack.

**Comment by EntropicPariah** [comment]
Titanium ingots are literally tagged as silver. This means that mods like Silent Gear assign it the stats that silver has and titanium ingots are then useless. I'd appreciate if you could provide the data pack to alter this behavior because I have zero experience with making them.

**Comment by kwpugh** [comment]
Removed tag in latest release.
