### ISSUE TITLE
[1.15.2] Warnings in Logfile

### ISSUE THREAD

**Issue by realTIMematrix** [kwpugh/easy_steel#3]
Hi,

I'm using the following mods:

Minecraft 1.15.2
Forge 31.0.1
EasySteel-1.15.2-1.1.24

Getting some messages in the logfile at startup and don't know if they have effect or interact with other mods and causes issues. If you can fix this this would be nice and reduce the lines of the logfile which helps :-)

`12:32:17.044 game [12:32:17] [Server-Worker-5/WARN] [minecraft/ModelBakery]: Exception loading blockstate definition: easy_steel:blockstates/titanium_block.json: java.io.FileNotFoundException: easy_steel:blockstates/titanium_block.json`
`12:32:17.058 game [12:32:17] [Server-Worker-5/WARN] [minecraft/ModelBakery]: Exception loading blockstate definition: 'easy_steel:blockstates/titanium_block.json' missing model for variant: 'easy_steel:titanium_block#'`
`12:32:17.379 game [12:32:17] [Server-Worker-5/WARN] [minecraft/ModelBakery]: Unable to load model: 'minecraft:item/steel_crossbow' referenced from: easy_steel:steel_crossbow#inventory: java.io.FileNotFoundException: minecraft:models/item/steel_crossbow.json`
`12:32:17.383 game [12:32:17] [Server-Worker-5/WARN] [minecraft/ModelBakery]: Unable to load model: 'minecraft:item/hardened_steel_crossbow' referenced from: easy_steel:hardened_steel_crossbow#inventory: java.io.FileNotFoundException: minecraft:models/item/hardened_steel_crossbow.json`
`12:32:17.494 game [12:32:17] [Server-Worker-5/WARN] [minecraft/ModelBakery]: Unable to resolve texture reference: #missingno in easy_steel:item/steel_crossbow_firework`
`12:32:17.494 game [12:32:17] [Server-Worker-5/WARN] [minecraft/ModelBakery]: Unable to resolve texture reference: #missingno in easy_steel:item/hardened_steel_crossbow_firework`

Thank you

**Comment by kwpugh** [comment]
I’ll take a look
