### ISSUE TITLE
[1.15.2] mod does not load easy_steel-general.toml from default config folder

### ISSUE THREAD

**Issue by realTIMematrix** [kwpugh/easy_steel#4]
Hi,

I'm using:

Minecraft: 1.15.2
Forge: 31.0.16
Easy Steel: 1.1.28

I recognized that you create two different .toml files. easy_steel-general.toml at start-up and easy_steel-server.toml after creating a new world. When you move both files to the defaultconfig folder (which forge creates) and delete the file in the config folder and the savegame then after the next start only the easy_steel-server.toml will be loaded from the default config path, but not the other one. this will be new created instead loading the file from defaultconfig. This is a problem for modpack developers who define the configuration and place all the configs in the defaultconfig folder.

`[03Feb2020 17:45:55.214] [modloading-worker-9/WARN] [net.minecraftforge.common.ForgeConfigSpec/CORE]: Configuration file C:\Users\Username\Documents\Minecraft\Modpacks\1.15.2\Test Pack\config\easy_steel-general.toml is not correct. Correcting`

`[03Feb2020 17:46:36.883] [Server thread/INFO] [net.minecraftforge.fml.config.ConfigFileTypeHandler/CONFIG]: Loading default config file from path C:\Users\Username\Documents\Minecraft\Modpacks\1.15.2\Test Pack\defaultconfigs\easy_steel-server.toml`

**Comment by kwpugh** [comment]
I'm not seeing that.   
- can you pastebin me a copy of the easy_steel-server.toml?
- what launcher are you using to build modpacks?

**Comment by kwpugh** [comment]
Can you try this version?   I think I eliminated it, but I can't be sure.

[EasySteel-1.15.2-1.1.29.jar.zip](https://github.com/kwpugh/easy_steel/files/4151019/EasySteel-1.15.2-1.1.29.jar.zip)

**Comment by kwpugh** [comment]
Fixed in latest release.
