### ISSUE TITLE
[Enhancement] Make crack hammer use ore dictionary

### ISSUE THREAD

**Issue by dierks-m** [kwpugh/easy_steel#5]
Title pretty much says it all.
It would be very helpful to then be able to let the mod that generates the most variety of ores do the generation and be able to use those universally.

Easy & Steel version: 1.1.29 on MC 1.15.2

**Comment by kwpugh** [comment]
Yep.  This is on my list and have been struggling to figure it out.  Since there is no Oredict anymore, I have been playing with block tag to no avail so far.   But I keep looking.

**Comment by kwpugh** [comment]
Added to v30.  Let me know what you think.
